project 'App.xcodeproj/'

# Uncomment the next line to define a global platform for your project
platform :ios, '12.4'

flutter_application_path = '../../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'App' do
	# Comment the next line if you don't want to use dynamic frameworks
	#use_frameworks!

	# Pods for App
	install_all_flutter_pods(flutter_application_path)

end
